GitHub workflows for image build and helm chart release
dfir-iris/iris-web pull request #420
Opened 2024-03-04 19:18 UTC by tylerobara

I have added some GitHub workflows that will build the container images for the database and app. I have also added a workflow that will release the helm chart when there are changes. 
Notes:
- One workflow per image `iriswebapp_db` and `iriswebapp_app`
  - The images will pushed to ghcr.io/dfir-iris/iriswebapp_{db, app}
  - The tags will be `main` if there is a push to main and the tag value if there is a release, example: `v2.4.6`
- Changed `docker-compose.yml` so that it will pull images from ghcr.io instead of building them
- The helm chart from `deploy/kubernetes` will be published to a gh-pages branch. After published the chart will be available for install by running
  ```
  helm repo add dfir-iris https://dfir-iris.github.io/iris-web/
  helm upgrade --install iris dfir-iris/iris-web --values my-custom-values.yaml
  ```
- Renamed `nginx_ingress.yaml` to `ingress.yaml` Reflects that the template already supports other Ingress classes such as Traefik
- Upgraded database base image to postgres 16

Images have been tested with docker-compose and k8s deployments

REQUIREMENTS IF PR IS ACCEPTED:
- create branch `gh-pages`
  - Ensure `gh-pages` is the default Pages branch at `Settings > Pages`
- Ensure packages availability is set to public [GitHub docs - packages](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility)
- Change branch `master` to `main` [GitHub docs -renaming](https://github.com/github/renaming)
  - Or change workflow triggers from `main` to `master`

2024-03-11 20:24 UTC, whikernel commented
Thanks a lot @tylerobara - amazing 🎉

2024-04-08 06:46 UTC, whikernel requested changes

2024-04-08 06:46 UTC, whikernel commented on docker/db/Dockerfile
> +FROM postgres:16-alpine
Let's rollback to 12 for the moment. We'll do the 12=>16 for a minor release, not a patch.

2024-04-08 06:46 UTC, whikernel commented on docker/db/Dockerfile
> +FROM postgres:16-alpine
```suggestion
FROM postgres:12-alpine
```

2024-04-08 06:49 UTC, whikernel requested changes

2024-04-08 06:49 UTC, whikernel commented on .github/workflows/build-db.yml
> +    branches: [ "main" ]
```suggestion
```
I would prefer to remove the push from master/main, because only the tagged releases should be used.

2024-04-08 06:49 UTC, whikernel commented on .github/workflows/build-nginx.yml
> +    branches: [ "main" ]
```suggestion
```

2024-04-08 06:49 UTC, whikernel commented on .github/workflows/build-webApp.yml
> +    branches: [ "main" ]
```suggestion
```

2024-04-11 23:43 UTC, tylerobara commented on .github/workflows/build-webApp.yml
> +    branches: [ "main" ]
removed

2024-04-24 13:55 UTC, whikernel approved these changes

2024-05-30 08:41 UTC, bpereto commented
can we merge this?

2024-06-28 13:33 UTC, merged